name: Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: 15 11 * * 5

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: ./scripts/build.sh
      - name: Run built image
        run: ./scripts/start.sh
      - name: Check (max 5 times) if docker images is running
        run: for i in {1..5}; do docker exec --tty ${{ github.event.repository.name }} env TERM=xterm docker info && break || sleep 10; done

  release:
    name: Release docker image
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push latest tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:latest

      - name: Build and push commit hash tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
